# general options
- hostname: localhost
- main_user: victor
- webmaster_email: admin@{{ hostname }}

# web
- web_files: /tmp/www

# git
- git_repos: /home/git
- git_sitename: Git Sources

# cloud
- cloud_db_password: nextcloud
- cloud_db_root_password: nextcloud

# reverse-proxy
- reverseproxy_db_password: npm
- reverseproxy_db_root_password: npm
