version: '3'

networks:
  proxy-tier:

services:
  db:
    image: postgres:alpine
    restart: always
    volumes:
      - ./volumes/db:/var/lib/postgresql
    env_file:
      - db.env


#########
## WEB ##

  web-builder:
    image: jekyll/jekyll
    restart: always
    command: jekyll build --watch --force_polling
    volumes:
      - ${WEB_FILES}:/srv/jekyll
      - ./volumes/web/html:/srv/jekyll/_site
      - ./volumes/web/jekyll-cache:/srv/jekyll/.jekyll-cache
    environment:
      - JEKYLL_ENV=production

  web-proxy:
    image: nginx:alpine
    restart: always
    expose:
      - 80
    volumes:
      - ./volumes/html:/usr/share/nginx/html:ro
      - ./web/nginx.conf:/etc/nginx/conf.d/default.conf
    environment:
      - VIRTUAL_HOST=${HOSTNAME}
#     - LETSENCRYPT_HOST=${HOSTNAME}
    depends_on:
      - web-builder
    networks:
      - proxy-tier


#########
## GIT ##

  git:
    image: jonashaag/klaus
    command: >-
      uwsgi --plugin python --http11-socket 0.0.0.0:80
      -w klaus.contrib.wsgi_autoreload --env KLAUS_REPOS=/repos
    expose:
      - 80
    restart: always
    volumes:
      - ./volumes/git:/repos
    environment:
      - VIRTUAL_HOST=git.${HOSTNAME}
#     - LETSENCRYPT_HOST=git.${HOSTNAME}
      - KLAUS_SITE_NAME="Git Sources"
    networks:
      - proxy-tier


###############
## NEXTCLOUD ##

  cloud-app:
    image: nextcloud:fpm-alpine
    restart: always
    volumes:
      - ./volumes/nextcloud:/var/www/html
    env_file:
      - ./cloud/env
    depends_on:
      - db

  cloud-proxy:
    image: nginx:alpine
    restart: always
    volumes:
      - ./volumes/nextcloud:/var/www/html:ro
      - ./cloud/nginx.conf:/etc/nginx/nginx.conf
    environment:
      - VIRTUAL_HOST=cloud.${HOSTNAME}
#     - LETSENCRYPT_HOST=cloud.${HOSTNAME}
    depends_on:
      - cloud-app
    networks:
      - proxy-tier
      - default

#################
## PROXY & SSL ##

  proxy:
    image: jwilder/nginx-proxy:alpine
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./proxy/uploadsize.conf:/etc/nginx/conf.d/uploadsize.conf
      - ./volumes/certs:/etc/nginx/certs:ro
      - ./volumes/vhost.d:/etc/nginx/vhost.d
      - ./volumes/html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy-tier

# ssl:
#   image: jrcs/letsencrypt-nginx-proxy-companion
#   restart: always
#   volumes_from:
#     - proxy
#   volumes:
#     - /var/run/docker.sock:/var/run/docker.sock:ro
#     - ./volumes/certs:/etc/nginx/certs
#   environment:
#     - DEFAULT_EMAIL=root@${HOSTNAME}

  ssl:
    image: paulczar/omgwtfssl
    restart: "no"
    volumes:
      - ./volumes/certs:/certs
    environment:
      - SSL_SUBJECT=${HOSTNAME}
      - CA_SUBJECT=admin@${HOSTNAME}
      - SSL_KEY=/certs/${HOSTNAME}.key
      - SSL_CSR=/certs/${HOSTNAME}.csr
      - SSL_CERT=/certs/${HOSTNAME}.crt
    networks:
      - proxy-tier
