version: '3'

networks:
  proxy-tier:

services:
  db:
    image: postgres:alpine
    container_name: db
    restart: always
    volumes:
      - ./volumes/db:/var/lib/postgresql/data
    env_file:
      - db.env


#########
## WEB ##

  web-builder:
    image: jekyll/jekyll
    container_name: web-builder
    restart: always
    command: jekyll build --watch --force_polling
    volumes:
      - ${WEB_FILES}:/srv/jekyll
      - ./volumes/web/html:/srv/jekyll/_site
      - ./volumes/web/jekyll-cache:/srv/jekyll/.jekyll-cache
    environment:
      - JEKYLL_ENV=production

  web-proxy:
    image: nginx:alpine
    container_name: web-proxy
    restart: always
    expose:
      - 80
    volumes:
      - ./web/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./volumes/web/html:/usr/share/nginx/html:ro
    environment:
      - VIRTUAL_HOST=${HOSTNAME}
      - LETSENCRYPT_HOST=${HOSTNAME}
    depends_on:
      - web-builder
      - proxy
    networks:
      - proxy-tier


#########
## GIT ##

  git:
    image: jonashaag/klaus
    container_name: git
    command: >-
      uwsgi --plugin python --http11-socket 0.0.0.0:80
      -w klaus.contrib.wsgi_autoreload --env KLAUS_REPOS=/repos --env KLAUS_USE_SMARTHTTP=1
    expose:
      - 80
    restart: always
    volumes:
      - ${GIT_REPOS}:/repos
    environment:
      - VIRTUAL_HOST=git.${HOSTNAME}
      - LETSENCRYPT_HOST=git.${HOSTNAME}
      - KLAUS_SITE_NAME=${GIT_SITENAME}
    depends_on:
      - proxy
    networks:
      - proxy-tier


###############
## NEXTCLOUD ##

  cloud-app:
    image: nextcloud:fpm-alpine
    container_name: cloud-app
    restart: always
    volumes:
      - ./volumes/nextcloud:/var/www/html
    env_file:
      - ./cloud.env
    depends_on:
      - db

  cloud-proxy:
    image: nginx:alpine
    container_name: cloud-proxy
    restart: always
    volumes:
      - ./cloud/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./volumes/nextcloud:/var/www/html:ro
    environment:
      - VIRTUAL_HOST=cloud.${HOSTNAME}
      - LETSENCRYPT_HOST=cloud.${HOSTNAME}
    depends_on:
      - cloud-app
      - proxy
    networks:
      - proxy-tier
      - default


#################
## PROXY & SSL ##

  proxy:
    image: jwilder/nginx-proxy:alpine
    container_name: proxy
    restart: always
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./proxy/uploadsize.conf:/etc/nginx/conf.d/uploadsize.conf:ro
      - ./volumes/proxy/certs:/etc/nginx/certs:ro
      - ./volumes/proxy/vhost.d:/etc/nginx/vhost.d
      - ./volumes/proxy/html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy-tier

  ssl:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: ssl
    restart: always
    volumes_from:
      - proxy
    volumes:
      - ./volumes/proxy/certs:/etc/nginx/certs
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - DEFAULT_EMAIL=admin@${HOSTNAME}


################
## WATCHTOWER ##

  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
