## general options
hostname: localhost
main_user: user
webmaster_email: admin@{{ hostname }}

## prod deployment
prod:
  - url: "{{ hostname }}"
    modules:
      - cloud
      - torrent

## cloud
# web
web_files: /tmp/www

# git
git_repos: /home/git
git_sitename: Git Sources

# cloud
cloud_db_password: nextcloud
cloud_db_root_password: nextcloud

## torrent
# transmission
transmission_username: transmission
transmission_password: transmission

## dev variables
gandi_key: helloworld
