#!/bin/bash
set -euo pipefail

DIR=$(cd "$(dirname "$0")/.." && pwd)

CONF=$DIR/conf/config.yml
PREFIX_AWS=dev

log () { echo -e "\e[33m\e[1m[·] $*\e[0m" ; }
# WARNING this function evaluates raw string vv
warn () { echo -e "\e[31m\e[1m[·] $*\e[0m"; "$@" ; }


## LOCAL

deploy_local () { vagrant up --provision ; }
destroy_local () { warn vagrant destroy ; }


## AWS

deploy_aws () {
    terraform apply
    ip=$(terraform output -no-color | grep -Eo '[0-9]+\.[0-9\.]+')
    hostname=$(yq -r '.hostname' "$CONF")
    gandi_key=$(yq -r '.gandi_key' "$CONF")

    ansible () {
        ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook -e "hostname=$PREFIX_AWS.$hostname" -u arch -i "$ip," --key-file ~/aws.pem "$DIR/playbooks/$1".yml
    }

    if [ -n "$playbooks" ]; then
        # run only specified playbooks
        for playbook in $playbooks; do
            ansible "$playbook"
        done
    else
        # run all playbooks
        ansible default
        ansible router
        ansible cloud
        ansible torrent
        ansible debug
    fi

    gandi_add () {
        curl -X POST \
            -H "authorization: Apikey $gandi_key" \
            -H 'content-type: application/json' \
            -d "{\"rrset_name\":\"$1\",\"rrset_type\":\"A\",\"rrset_values\":[\"$ip\"],\"rrset_ttl\":300}" \
            "https://api.gandi.net/v5/livedns/domains/$hostname/records"
    }
    gandi_add "$PREFIX_AWS"
    gandi_add "*.$PREFIX_AWS"
}

destroy_aws () {
    ip=$(terraform output -no-color | grep -Eo '[0-9]+\.[0-9\.]+')
    hostname=$(yq -r '.hostname' "$CONF")
    warn terraform destroy
    if [ -n "$ip" ]; then
        gandi_key=$(yq -r '.gandi_key' "$CONF")
        warn curl -X DELETE -H "authorization: Apikey $gandi_key" "https://api.gandi.net/v5/livedns/domains/$hostname/records/dev"
        warn curl -X DELETE -H "authorization: Apikey $gandi_key" "https://api.gandi.net/v5/livedns/domains/$hostname/records/*.dev"
    else
        log "no DNS record registered"
    fi
}


## PROD

deploy_prod () {
    # config file is a list of (url, modules) pairs
    # prod:
    #   - url: domain.tld
    #     modules:
    #       - a
    #       - b

    yq -cr '.prod[]' "$CONF" | while read -r host; do
        url=$(yq -cr '.url' <<< "$host")
        # at first, deploy 'default' playbook
        ansible-playbook -i "$url," "$DIR/playbooks/default.yml"

        yq -cr '.modules[]' <<< "$host" | while read -r module; do
            ansible-playbook -i "$url," "$DIR/playbooks/$module".yml
        done
    done
}

destroy_prod () { echo "4B0RT 4ND K1LL" ; echo "sudo rm -rf /" ; }


## MAIN

help () {
    echo "$0 help:"
    echo -e "    deploy"
    echo -e "      local  deploy on localhost using vagrant and libvirt"
    echo -e "      aws    deploy on aws using terraform and set cname on gandi"
    echo -e "      prod   deploy on production"
    echo -e "    destroy  local | aws | prod | all"
    echo -e "    ssh      local | aws | prod"
}

if [ "$#" -lt 2 ]; then
    help
    exit
fi

action=$1
env=$2
shift
shift
playbooks=$*

case "$action" in
    deploy)
        case "$env" in
            local) deploy_local ;;
            aws)   deploy_aws ;;
            prod)  deploy_prod ;;
            *)     help ;;
        esac
        ;;
    destroy)
        set +e
        case "$env" in
            local) destroy_local ;;
            aws)   destroy_aws ;;
            prod)  destroy_prod ;;
            all)   destroy_local; destroy_aws; destroy_prod ;;
            *)     help ;;
        esac
        ;;
    ssh)
        case "$env" in
            local) vagrant ssh ;;
            aws)   ssh -i ~/aws.pem "arch@$(terraform output -no-color | grep -Eo '[0-9]+\.[0-9\.]+')" ;;
            prod)  ssh "$(yq -r '.main_user' "$CONF")@$(yq -r '.hostname' "$CONF")" ;;
            *)     help ;;
        esac
        ;;
    *) help ;;
esac

# vim: ts=4 sw=4 et:
