# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "generic/arch"
  config.vm.provider :libvirt do |lv|
    lv.cpus = "2"
    lv.memory = "2048"
  end

  config.vm.define :host do |host|
    [80, 443, 3000, 8080, 9091, 22000, 51413].each do |port|
      config.vm.network :forwarded_port, guest: port, host: port
    end
    #host.vm.network :private_network, ip: "192.168.42.69"
    host.vm.hostname = "host"
  end

  ["default", "router", "cloud", "torrent", "debug"].each do |pb|
    config.vm.provision :ansible do |ansible|
      ansible.playbook = "../playbooks/" + pb + ".yml"
      ansible.extra_vars = {hostname: "host"}
      }
    end
  end
end
