- hosts: all
  become: yes
  vars_files:
    - ../conf/config.yml

  tasks:

    - name: Start Cloudflare tunnel
      community.docker.docker_container:
        name: tunnel
        image: cloudflare/cloudflared
        restart_policy: unless-stopped
        # healthcheck:
          # test: <test>
        command:
          - tunnel
          - run
          - --token={{ cloudflare_token }}
        networks:
          - name: public


    ############
    ### Homepage

    - name: Copy config files
      ansible.builtin.copy:
        src: ../conf/home
        dest: /mnt/conf
        mode: preserve

    - name: Start home page
      community.docker.docker_container:
        name: home
        image: b4bz/homer:latest
        restart_policy: unless-stopped
        env:
          PORT: "80"
          INIT_ASSETS: "0"
        volumes:
          - /mnt/conf/home:/www/assets:ro
        networks:
          - name: private
            ipv4_address: 172.20.0.5


    #######
    ### DNS

    - name: Start DNS provider
      community.docker.docker_container:
        name: dns
        image: pihole/pihole:latest
        restart_policy: unless-stopped
        env:
          TZ: Europe/Paris
          WEBPASSWORD: "{{ dns_password }}"
          DNSMASQ_LISTENING: all
        ports:
          - "53:53/tcp"
          - "53:53/udp"
        volumes:
          - /mnt/dns/etc-pihole:/etc/pihole
          - /mnt/dns/etc-dnsmasq.d:/etc/dnsmasq.d
        networks:
          - name: private
            ipv4_address: 172.20.0.2

    - name: "Configure firewall: allow DNS"
      community.general.ufw:
        rule: allow
        app: dns


    #######
    ### VPN

    - name: Start VPN
      community.docker.docker_container:
        name: vpn
        image: weejewel/wg-easy
        restart_policy: unless-stopped
        healthcheck:
          test: wget -qO- localhost:51821 | grep -q '<title>WireGuard</title>'
        env:
          WG_HOST: "vpn.{{ hostname }}"
          PASSWORD: "{{ vpn_password }}"
          WG_PERSISTENT_KEEPALIVE: "10"
          WG_DEFAULT_ADDRESS: 10.0.0.x
          # Setting this as the inventory_hostname (ie public IP) causes timeouts
          # WG_DEFAULT_DNS: "{{ inventory_hostname }}"
          WG_DEFAULT_DNS: 172.20.0.2  # DNS private IP
        ports:
          - "51820:51820/udp"
        volumes:
          - /mnt/vpn:/etc/wireguard
        capabilities:
          - NET_ADMIN
          - SYS_MODULE
        sysctls:
          net.ipv4.conf.all.src_valid_mark: "1"
          net.ipv4.ip_forward: "1"
        networks:
          - name: public
          - name: private
            ipv4_address: 172.20.0.3

    - name: "Configure firewall: allow Wireguard"
      community.general.ufw:
        rule: allow
        port: "51820"
        proto: udp
