#!/bin/bash

# If the user is not root
if [ "$USER" != "root" ]
then

	# Dislpay a notice and stop
	echo "Sorry, only root can use this command."
	exit 1

fi

# Read in the SSH key
echo "Input the key to be added:"
read -r key

keyfile=$(mktemp)
echo "$key" > "$keyfile"

# Generate a fingerprint
fingerprint=$(ssh-keygen -lf "$keyfile")

# Check for errors
if [ "$(echo "$fingerprint" | grep -Ec '(R|D)SA')" -eq 0 ]
then

	# Display the fingerprint error and clean up
	echo "Error: $fingerprint"
	exit 1

fi

# Add the key to the authorised keys file and clean up
mkdir -p ssh && \
	echo -n "no-agent-forwarding,no-port-forwarding,no-X11-forwarding " >> ssh/authorized_keys && \
	cat "$keyfile" >> ssh/authorized_keys && \
	chmod 700 ssh && \
	chmod 600 ssh/authorized_keys

rm "$keyfile"

# Display the fingerprint for reference
echo "Success! Added a key with the following fingerprint:"
echo "$fingerprint"
